#!/usr/bin/bash
#
# alert-uptime-helper
# Author:       Klaus Wenninger <kwenning@redhat.com>, February 2026
# License:      GPLv2+
# Copyright:    (c) 2026 Red Hat, Inc.
# Version:      1.0.0
#
# This alert agent tracks node join times in the cluster by recording a timestamp
# when a node comes online. This is used by fence_sync_site on older Pacemaker
# versions that don't provide a native #uptime attribute.
#
# Configure the alert with crmsh:
#
# crm configure alert uptime-1 "/usr/bin/alert-uptime-helper" select nodes attributes join_attribute=node_join_time
#
# Configure the alert with pcs:
#
# pcs alert create id=alert-uptime-1 path=/usr/bin/alert-uptime-helper options join_attribute=node_join_time
# cibadmin --modify --scope alerts --xml-text '<alert id="alert-uptime-1"> <select> <select_nodes /> </select> </alert>'
#

logger_tag="alert-uptime-helper"
logger="/usr/bin/logger"

# Environment variables set by cluster
crm_alert_kind="${CRM_alert_kind:-manual call}"
crm_alert_node="${CRM_alert_node:-$HOSTNAME}"
crm_alert_desc="${CRM_alert_desc:-no description provided}"

# Configurable join attribute name (default: node_join_time)
join_attribute="${join_attribute:-node_join_time}"

$logger -t "$logger_tag" "AH: begin event '$crm_alert_kind' for node '$crm_alert_node' ($crm_alert_desc)"

function process_node_event() {
    local node="$crm_alert_node"
    local desc="$crm_alert_desc"

    $logger -t "$logger_tag" "INFO: Node event for '${node}': ${desc}"

    case "$desc" in
        member|online)
            # Node has joined the cluster - record the join time
            local join_time
            join_time=$(date +%s)

            $logger -t "$logger_tag" "INFO: Recording join time ${join_time} for node ${node} in attribute ${join_attribute}"

            # Set the join time attribute
            /usr/sbin/crm_attribute --node "${node}" --name "${join_attribute}" --update "${join_time}" --lifetime forever
            rc="$?"

            if [[ "$rc" == "0" ]]; then
                $logger -t "$logger_tag" "INFO: Successfully recorded join time for node ${node}"
            else
                $logger -t "$logger_tag" "ERR: Failed to record join time for node ${node}, rc=${rc}"
            fi
            ;;
        offline|lost|shutdown)
            # Node has left the cluster - optionally clean up the attribute
            $logger -t "$logger_tag" "INFO: Node ${node} left cluster (${desc})"
            # Note: We don't delete the attribute here as it will be cleaned up automatically
            # when the node rejoins, and keeping it doesn't cause issues
            ;;
        *)
            $logger -t "$logger_tag" "INFO: Unhandled node state for ${node}: ${desc}"
            ;;
    esac
}

case "$crm_alert_kind" in
    node|nodes)
        process_node_event
        ;;
    *)
        msg="Unhandled '$crm_alert_kind' alert (${crm_alert_desc})"
        $logger -t "$logger_tag" "INFO: $msg"
        ;;
esac

$logger -t "$logger_tag" "AH: end event '$crm_alert_kind'"
exit 0
